### ISSUE TITLE
Command does not show up in command palette

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/graph-analysis#12]
<img width="1528" alt="Screenshot 2021-10-30 15 20 38" src="https://user-images.githubusercontent.com/73286100/139534355-01cdf398-2f64-439c-b6f3-350ef51d33e2.png">

I tried: 
- restarting
- disabling & re-enabling the plugin
- reinstalling the plugin
:(

**Comment by SkepticMystic** [comment]
We did change something about when the command shows up, but I _think_ it will only be hidden from the cmd palette if the view is already open somewhere

**Comment by chrisgrieser** [comment]
can confirm, works now :)
