### ISSUE TITLE
The number of notes in my vault exceeds 10,000, and obsidian always crashes when using this plugin.

### ISSUE THREAD

**Issue by tyf2018** [SkepticMystic/graph-analysis#13]
Thank you for your development work, I feel that this plugin is very helpful to me.

Unfortunately, the number of notes in my vault exceeds 10,000, and obsidian always crashes when using this plugin.

**Comment by SkepticMystic** [comment]
Oh wow... haha yeah that might be an issue.
Do you get any errors in the console when this happens?
You may need to enable `Preserve Log` in the console to make sure the message doesn't disappear:
![image](https://user-images.githubusercontent.com/70717676/139538400-e5b3fbe3-a3ab-41c8-8246-370352a68f7f.png)

**Comment by tyf2018** [comment]
@SkepticMystic    Please check😊

[obsidian.md-1635649375853.log](https://github.com/SkepticMystic/graph-analysis/files/7447975/obsidian.md-1635649375853.log)

**Comment by SkepticMystic** [comment]
@tyf2018 please check if this is resolved in the latest version :)
If not, we may just need to wait longer for the vault to finish loading

**Comment by tyf2018** [comment]
> @tyf2018 please check if this is resolved in the latest version :) If not, we may just need to wait longer for the vault to finish loading

This version still crashes 🤣

**Comment by HEmile** [comment]
Is it possible to show the log you are getting now?

**Comment by tyf2018** [comment]
> Is it possible to show the log you are getting now?

After opening the latest version of the plug-in, Obsidian crashed immediately. Please check.

[obsidian.md-1635753808409.log](https://github.com/SkepticMystic/graph-analysis/files/7451598/obsidian.md-1635753808409.log)

**Comment by SkepticMystic** [comment]
@tyf2018 can you try 0.1.0 and see if that changes anything. It's possible the error is unrelated to what we fixed, though

**Comment by tyf2018** [comment]
> @tyf2018 can you try 0.1.0 and see if that changes anything. It's possible the error is unrelated to what we fixed, though

This time it has been improved a bit, but it will crash after opening the plug-in for about ten seconds or so.

[obsidian.md-1635757498907.log](https://github.com/SkepticMystic/graph-analysis/files/7452011/obsidian.md-1635757498907.log)

**Comment by HEmile** [comment]
Thank you for sharing. I think there might be a crash related to you using Chinese symbols. We'll look into it!

**Comment by tyf2018** [comment]
Great, the new version won't crash anymore!

**Comment by SkepticMystic** [comment]
Hahaha that's great! Not sure exactly what fixed it, but happy to hear it's working

**Comment by HEmile** [comment]
Haha, I was going to try to debug this... Glad to hear it works!
