### ISSUE TITLE
Any recommendation of reading materials on the algorithms ?

### ISSUE THREAD

**Issue by vizance** [SkepticMystic/graph-analysis#14]
Thanks for this POWERFUL plugins ! It's really helpful when I do my writing works.

I'm also interested in algorithms that this plugin uses (Jaccard Similarity, Jaccard Similarity... etc ). Is there any recommendation of book or video on this topic?

Thank you !

**Comment by SkepticMystic** [comment]
Ahh yes, definitely! I will add this to the Readme, but here is the link to the Neo4j algorithm documentation: https://neo4j.com/docs/graph-data-science/current/algorithms/.
This is where I learned about all the algs besides co-citations

**Comment by vizance** [comment]
Wow thank you, the doc is really helpful to know the algs.

About the co-citations, it there any reading material?

**Comment by SkepticMystic** [comment]
Sure thing :)
For co-cites, we really just used the [wikipedia page](https://en.wikipedia.org/wiki/Co-citation)!

**Comment by vizance** [comment]
Got it! will read wikipedia page first.

**Comment by SkepticMystic** [comment]
And if you like, you can see how we implement each of the algs starting here in the code: https://github.com/SkepticMystic/graph-analysis/blob/b5c20ded34b0052f2566a3a20d973e6892986594/src/MyGraph.ts#L67
