### ISSUE TITLE
Hover preview doesn't work

### ISSUE THREAD

**Issue by phlind** [SkepticMystic/graph-analysis#16]
Pressing Cmd and hovering over a note does only show an empty popover.

**Comment by SkepticMystic** [comment]
Thanks phlind. I will push a fix soon

**Comment by SkepticMystic** [comment]
Working on my end in 0.1.7. Very weird bug, not sure what's happening, but I reverted back to the old behaviour

**Comment by phlind** [comment]
Yes, it's working now. 👍
