### ISSUE TITLE
Suggested link doesn't disappear after linking

### ISSUE THREAD

**Issue by phlind** [SkepticMystic/graph-analysis#18]
The plugin predicted a link. After actually putting the link in the note and pressing "refresh" the list gets expanded by several other notes, but the suggestions still include the note already linked.

**Comment by SkepticMystic** [comment]
I guess this isn't a bug. The link prediction algorithms don't exclude a note if they are already linked. But that's a good feature request, I think. Perhaps there can be a setting for this.
I like seeing which are actually linked and which aren't. If you inspect the element, you'll see I've added a class to each table row indicating whether or not that note is linked to the current note. This gives you the ability to style the row based on whether they're connected. For example, this snippet will make linked nodes more transparent:
```css
tr.analysis-linked {
    opacity: 0.3;
}
```
![image](https://user-images.githubusercontent.com/70717676/139862955-75284ff5-0ced-4548-bf6e-caa353a16fe0.png)

**Comment by SkepticMystic** [comment]
You can even go so far as to `display: none;` the linked notes to hide them from the table:
```css
tr.analysis-linked {
    display: none;
}
```
