### ISSUE TITLE
Would you consider adjusting the layout of the user panel?

### ISSUE THREAD

**Issue by tyf2018** [SkepticMystic/graph-analysis#27]
Super awesome plug-in, my library has more than 10,000 notes, the new version of the plug-in no longer crashes, I am very happy!

Have a small suggestion, Would you consider adjusting the layout of the user panel? For example, like the longform plug-in, it is made into a tab instead of a drop-down menu. When switching the algorithm mode, the drop-down menu always needs a few extra points 1-2 times, and it is not intuitive

The design of the tab looks like this:
![image](https://user-images.githubusercontent.com/56342788/140597249-e3839419-1c99-454b-afb2-a598cf9667a5.png)

**Comment by SkepticMystic** [comment]
Hey Tyf!
Thanks for the suggestion. I want to clarify, what do you mean it needs an extra few points 1-2 times? Also, in what way do you find it unintuitive? Is there a way of keeping the current setup but make it more user friendly?

I say this because using tabs like on Longform would probably take up more space than the dropdown. Especially if more algorithms are added, you know?

**Comment by tyf2018** [comment]
> Hey Tyf! Thanks for the suggestion. I want to clarify, what do you mean it needs an extra few points 1-2 times? Also, in what way do you find it unintuitive? Is there a way of keeping the current setup but make it more user friendly?
> 
> I say this because using tabs like on Longform would probably take up more space than the dropdown. Especially if more algorithms are added, you know?

Hey, thanks for the answer.

What I mean is that the drop-down menu requires 1-2 more mouse clicks. I personally think that the interactive interface of tabs is easier to operate.
The drop-down menu needs to click the drop-down box so that the user can see which algorithm types are available, not as clear as a tab. Therefore, I personally feel that it is a bit unintuitive.

The interactive interface I envisioned, for example, looks like this，I think this method should not take up additional space.
![图2021-11-07 excalidraw](https://user-images.githubusercontent.com/56342788/140634371-97e8ce75-01fe-4e03-ab4e-a3886d6292a6.png)

**Comment by SkepticMystic** [comment]
I think if I can figure out how to make the tab list scrollable, this would work well

**Comment by SkepticMystic** [comment]
Got a nice little scroll bar working :)
I'll keep working on the rest of the changes soon

**Comment by SkepticMystic** [comment]
![GA-Scrollbar](https://user-images.githubusercontent.com/70717676/140637438-f0db9f93-13b3-472f-9010-e4bcea704d6e.gif)

Here's what I got so far

**Comment by tyf2018** [comment]
> ![GA-Scrollbar](https://user-images.githubusercontent.com/70717676/140637438-f0db9f93-13b3-472f-9010-e4bcea704d6e.gif)
> 
> Here's what I got so far

So cool！

**Comment by SkepticMystic** [comment]
@tyf2018 checkout 0.6.4! Lots of changes to the ui :)

**Comment by tyf2018** [comment]
> @tyf2018 checkout 0.6.4! Lots of changes to the ui :)

Awesome, the problem was solved in just one day! Incredible!

Here is a small question, how can I make the scroll bar thicker? How to modify css? For me, the scroll bar is too thin, and sometimes it is not convenient to drag. thanks.
![image](https://user-images.githubusercontent.com/56342788/140684248-747b255f-9480-4b4d-8e12-f0d3594bd0a6.png)

**Comment by SkepticMystic** [comment]
Ahh I see. 
Do you know you can `Shift + Scroll` to make the scroll bar move horizontally?
But aside from that, I will send a css snippet you can use to make it thicker at some point today :)

**Comment by tyf2018** [comment]
I learned a little trick, thank you. However, Shift + Scroll does not work on my computer, and the reason has not been found out yet.

**Comment by SkepticMystic** [comment]
Weird... alright, but here's a snippet you can use to change the height :)
```css
.GA-View .scrollContainer:hover ::-webkit-scrollbar {
  height: 8px;
}
```
This will double the height, but change it as needed

**Comment by SkepticMystic** [comment]
I'm gonna close this issue @tyf2018.
If it bothers you that Shift + scroll doesn't work, please open a separate issue for it :) I can look into it sometime
