### ISSUE TITLE
Tags to exclude specific notes

### ISSUE THREAD

**Issue by Nissentott** [SkepticMystic/graph-analysis#28]
Request as per discussion from the Discord channel: 

While the regex exclusion is great, I think it would also be a good idea to be able to **exclude** specific notes by more simple ways like the usage of **tags**.

My concern would for example be when I want to exclude my **structure notes/MoC** from the lists in your plugin, since they tend to gather in the top of the lists and I don't want to see them as they are deliberately chosen links in the first place.

Great Plugin!

**Comment by SkepticMystic** [comment]
@Nissentott this is now possible in 0.10.0! Please let us know if it works as expected :)

**Comment by FelipeRearden** [comment]
> @Nissentott this is now possible in 0.10.0! Please let us know if it works as expected :)

Working on version `0.10.3` in Obsidian `0.12.19` !
