### ISSUE TITLE
How is the co-citation feature different form Backlinks ? And Zotero integration ?

### ISSUE THREAD

**Issue by bpriyum** [SkepticMystic/graph-analysis#34]
HI, 

I am basing my query totally on the image that you have attached here. The backlinks panel allow shows the number of times a page has been mentioned in other pages. So, I don't see how the co-citation feature is any different.

Also, have you thought of integrating it with citations pulled from Zotero ?

**Comment by SkepticMystic** [comment]
Hey @bpriyum!
So, backlinks says: "The current note is linked in this note".
CoCites says: "The current notes is linked with this note in that note".
I dunno if that makes sense? Checkout the wiki page if not: https://en.wikipedia.org/wiki/Co-citation

About Zotero, I'm not sure what you mean. How would that work?
