### ISSUE TITLE
The Setting doesn't work after 0.10.0 update

### ISSUE THREAD

**Issue by Liong1976** [SkepticMystic/graph-analysis#36]
The setting doesn't show anything after the 0.10.0 update

![image](https://user-images.githubusercontent.com/88898230/141646959-a3edb9f1-90be-4b66-83e6-914bfe1ef0bf.png)

**Comment by SkepticMystic** [comment]
@Liong1976 thanks for noting this!
After the big update to 0.10.0, I didn't realise this was broken. Should be fixed in 0.10.1

**Comment by Liong1976** [comment]
You are most welcome, @SkepticMystic!
