### ISSUE TITLE
[FR] Update the Caret Position of the Active Note when Selecting a Note in GA

### ISSUE THREAD

**Issue by FelipeRearden** [SkepticMystic/graph-analysis#38]
More details about his FR here #37

**Comment by SkepticMystic** [comment]
Working in 0.10.2 :)

**Comment by FelipeRearden** [comment]
> Working in 0.10.2 :)

FANTASTIC !!!! Thank you very much @SkepticMystic !!!!

Just like Advanced Cursors :)

Working on version `0.10.2` Obsidian `0.12.19`


I wish you a fantastic day!!!!
