### ISSUE TITLE
What means 'NLP plugin'?

### ISSUE THREAD

**Issue by artem-barmin** [SkepticMystic/graph-analysis#49]
Tried to search for NLP plugins in community library - have not found any.

**Comment by SkepticMystic** [comment]
The plugin is not available on the community plugin list yet. You either have to install it manually, or using the BRAT plugin. I recommend using BRAT.

**Comment by shaggyfeng** [comment]
> The plugin is not available on the community plugin list yet. You either have to install it manually, or using the BRAT plugin. I recommend using BRAT.

Do you mean the [Beta Reviewers Auto-update Tester plugin](https://github.com/TfTHacker/obsidian42-brat) ? Can you provide links for the 2 plugins?

**Comment by SkepticMystic** [comment]
@shaggyfeng exactly yeah.
So that's the link to BRAT, plus you can find it on the plugin list in Obsidian. And you're already on the NLP plugin repo here :yum:

**Comment by bhundt** [comment]
Hmm I have the same issue. I installed BRAT and in BRAT I added this repository but I still get the message "The NLP plugin must be installed"...any idea what I am doing wrong?

**Comment by SkepticMystic** [comment]
It's possible that installing I BRAT didn't _enable_ the plugin. So go to your plugin list, refresh, and enable NLP.
Let me know if that works

**Comment by bhundt** [comment]
So I did the following:

1. Uninstalled BRAT as well as current version of Graph-Analysis plugins
2. Restarted Obsidian
3. Installed BRAT plugin
4. Restarted Obsidian
5. In BRAT added this repository ("SkepticMystic/graph-analysis") as a beta plugin
6. Activated the graph-analysis plugin in Obsidian plugin list
7. Restarted Obsidian
8. Update of all plugins
9. Restarted Obsidian

Unfortunately this did not solved the error message "The NLP plugin needs to be installed". I currently have version 0.15.3 of the graph-analysis plugin installed.

Attached a screenshot of the error message which is only shown when certain algorithms are used (for example "Sentiment" or "Otsuka-Chai". "Co-Citations", "HITS" and some more are working finde.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/97769/149269163-28b1ba7d-10d7-4e5a-90bd-0b6b14b67c1f.png">

**Comment by SkepticMystic** [comment]
@bhundt sorry, I didn't see which repo we were in!
The NLP plugin can be found here: https://github.com/SkepticMystic/nlp
You've got to install it via BRAT, and enable this setting in the NLP settings:
![image](https://user-images.githubusercontent.com/70717676/149271859-836c540a-dfc3-4fef-8925-f49bf1c8110a.png)

Please let me know if that works

**Comment by bhundt** [comment]
Ahhhh that makes a lot more sense now. Thanks, solved the issue!
